### ISSUE TITLE
notify more than one Telegram chat id

### ISSUE THREAD

**Issue by yleyvag** [thp/urlwatch#211]
I tried this:

```
report:
    telegram:
       bot_token: '#'
        chat_id: '#'
        enabled: true
    telegram:
       bot_token: '#'
       chat_id: '#'
       enabled: true
```
But it didn't worked for both chat_id, it just sent the notification to the last one. There's any way I can notify both chat ids?
