### ISSUE TITLE
Question: How can I set a cookie?

### ISSUE THREAD

**Issue by ghost** [thp/urlwatch#264]
I've seen that support for cookies got implemented. But I can't really figure out how to set them in the urls.yaml file. What parameters can be used?

**Comment by thp** [comment]
Use the YAML syntax:

```
url: http://example.com/
cookies:
    Key: ValueForKey
    OtherKey: OtherValue
```
