### ISSUE TITLE
Ability to select element by count

### ISSUE THREAD

**Issue by maximbaz** [thp/urlwatch#266]
Let's say you want to setup a watch on this page: https://github.com/thp/urlwatch/releases

I can't find a way to focus urlwatch to only the latest tag.

Here's a filter I could come up with: 

```
filter: element-by-class:main,element-by-class:tag-name,html2text
```

But the latest tag is not identifiable by id or class.

I can see this being solved with something like this:

```
filter: element-by-class:main,element-by-count:0,element-by-class:tag-name,html2text

**Comment by thp** [comment]
This should now be possible with `xpath` support.

Also, for checking the urlwatch version in particular, there's the example with the urlwatch webpage and `filter: html2text,grep:Current.*version,strip` in the example urls.yaml :)

Here's an xpath example:

```
url: https://thp.io/2008/urlwatch/
filter:
    - xpath: '//*[@id="content"]/ul[2]'
    - html2text: re
```

**Comment by maximbaz** [comment]
Awesome news, thanks for letting me know!

For reference, here's a working example for monitoring tags on Github:

```
url: "https://github.com/thp/urlwatch/releases/latest"
filter:
  - xpath: '(//div[contains(@class,"release-timeline-tags")]//h4)[1]/a'
  - html2text: re
```
