### ISSUE TITLE
XPath filtering doesn't seem work on XML files

### ISSUE THREAD

**Issue by dpeukert** [thp/urlwatch#281]
Will investigate further, but it looks like the XPath filter always returns a None when used on an XML file (e. g. RSS feed).

Example feed: https://heronebag.com/blog/index.xml

Example `urls.yaml`:
```yaml
name: "herOneBag.com"
url: "https://heronebag.com/blog/index.xml"
filter: xpath://item
```

Basic XML also doesn't work: https://www.w3schools.com/xml/note.xml
