### ISSUE TITLE
sendmail: what method is the correct one? should I setup sendmail independently? can msmtp be used instead? : (

### ISSUE THREAD

**Issue by foice** [thp/urlwatch#376]
After reading several issues this is my best attempt to get sendmail output to work, but seems not to be enough. 
One thing that is unclear looking at the main page and the issue is wether I have to put it     `method: smtp` or     `method: sendmail`. Furthermore a crucial step may have gone untold. The config in urlwatch should be enough for sendmail to work or I must configure sendmail to work independently even outside urlwatch? (in the latter case I had better luck with msmtp, is it possible to use that instead?
```
report:
  email:
    enabled: true
    from: '~~~~~~~@gmail.com'
    html: false
    method: smtp
    sendmail:
      path: '/usr/sbin/sendmail'
    smtp:
      host: smtp.gmail.com
      keyring: true
      port: 587
      starttls: true
      user: '~~~~~~~~~@gmail.com'
    subject: '{count} changes: {jobs}'
    to: '||||||||||@gmail.com'
```
