### ISSUE TITLE
Feature Request: templates/groups with specific Options. 

### ISSUE THREAD

**Issue by nille02** [thp/urlwatch#381]
I think it would be useful to add templates or groups. I migrate some of my Monitors from distill to urlwatch and most of my jobs are the same, except for url and name settings. 

Maybe with a new config file "templates.yaml" or "groups.yaml" that is close to the job/url list or direct in the urls.yaml. But I would prefer a new file because its not a job/url. 

For Example: 

```
kind: group
name: "sidemaps"
filter:
    - xpath: 
        path: "//div[contains(@class,'sitemap')]/div[contains(@class,'text-left')]"
        exclude: "//div[contains(@class,'ad-tag ad-tag1')] | //div[contains(@class,'ad-tag ad-tag2')] | //div[contains(@class,'ad-tag ad-tag3')]"
---
kind: group
name: "amazon-availability"
filter:
    - xpath: "//div[contains(@id,'availability')]"
```

In my urls.yaml then i just refer to the template/group like

```
kind: url
name: "Website 1"
group/template: "sidemaps"
url: https://example.tld/sidemap/
---
kind: url
name: "Hot Deal"
group/template: "amazon-availability"
url: https://www.amazon.tld/dp/GFDHZ6378H/
```

It would reduce the repeating lines, make the urls.yaml more readable (specific if you use many jobs. i'm close to 1500) and it would be much easier to add new urls on the cli again without edit the file afterwards manual. 

For Example:

`urlwatch --add url=https://example.tld/sidemap/,name='Website 2',group='sidemaps'`
`urlwatch --add url=https://amazon.tld/out-of-stock/,name='Again new deal',group='amazon-availability'`

Maybe this can be combined with #379 so that after adding it the job can get launched without do all jobs. 

Thanks in advance for reading and i hope its understandable what i mean.
