### ISSUE TITLE
What is syntax for login by cookies

### ISSUE THREAD

**Issue by Hitaro** [thp/urlwatch#391]
![ation](https://user-images.githubusercontent.com/18015032/57077887-626a3300-6d02-11e9-8c42-3afac812af67.png)

I want to login to [Zabbix ](https://www.zabbix.com)with above cookies. How should I add them to `urls.yaml` file?

**Comment by cfbao** [comment]
```yaml
kind: url
url: https://www.zabbix.com/
cookies:
    <name_1>: <value_1>
    <name_2>: <value_3>
    ...
```
