### ISSUE TITLE
Sort filter?

### ISSUE THREAD

**Issue by jesjimher** [thp/urlwatch#397]
First of all, thanks a lot for such a great piece of software, it's made my life easier in a lot of ways.

Just a humble suggestion. I'm monitoring a website whose content is a listing that doesn't appear to be in any particular order (it probably comes from a DB without applying any ordering in the query). So, every time webpage loads this listing is shown in a non-predictable order, and urlwatch interprets it as a change and leads to a lot of false positives where content is actually the same, just in different order.

I haven't found any way to sort scraped content with any of available filters, so perhaps adding a "sort" filter would be a smart way of solving this kind of cases.

Thanks!

**Comment by bretterism** [comment]
I know this issue is old, but I ran into a similar situation. Since I didn't find any features available, I wrote a custom hook that sorts the data before the comparison.

```
class CustomSortFilter(filters.FilterBase):
     """Custom filter for sorting before comparison"""
     __kind__ = 'sort'

     def filter(self, data, subfilter=None):
         data_list = data.splitlines()
         data_list = sorted(data_list)

         return '\n'.join(data_list)
```

I added this filter at the end of my filter chain, like so:
```
 filter:
     - strip:
     - element-by-id: gmaplinks
     - html2text:
         method: pyhtml2text
         unicode_snob: true
         ignore_images: true
         ignore_links: true
     - sort:
```

Hopefully this helps others who are needing a quick solution to sort their results!
