### ISSUE TITLE
support XML namespace in XPath filter

### ISSUE THREAD

**Issue by olifre** [thp/urlwatch#403]
Trying the following configuration:
```yaml
filter: 
  - xpath:   
      path: '//EntityDescriptor'
      method: xml
kind: url
url: http://www.aai.dfn.de/fileadmin/metadata/dfn-aai-test-metadata.xml
```
I get an empty result instead of all `EntityDescriptor` tags. 

Is this some kind of lxml limitation I am hitting here?
