### ISSUE TITLE
Grep options?

### ISSUE THREAD

**Issue by jprokos** [thp/urlwatch#452]
It would be helpful to use grep options:

`-i, --ignore-case`

Is this possible? Can we set this in the config file somehow?

If this is already possible would someone provide a working example or notate it in the man page?

**Comment by cfbao** [comment]
No grep command line options are supported. Urlwatch doesn't actually use the `grep` utility internally.

However, you can use the inline flag `(?i)` to turn on case insensitive mode.
https://www.regular-expressions.info/modifiers.html#bodytext
https://docs.python.org/3/library/re.html#re.I

**Comment by jprokos** [comment]
Thanks, this is exactly what I needed.
Please provide an example of using the inline flag in a urlwatch filter. I am not sure of the placement.

**Comment by jprokos** [comment]
Thanks, this is exactly what I needed.
Here is an example that works for me:

`- grep: (?i)olympic`

**Comment by jprokos** [comment]
Thank you so much, this is exactly what I needed. I found the answers to my other questions using your first link. I couldn't find that information. 

Here is an example that works for me:

`- grep: (?i)olympic`

And when searching for more than one string the first inline flag affects the entire line.

`- grep: (?i)olympic|time standards|2020`
The case will stay the same for the entire expression.

If you want to specify case sensitivity in the middle of the expression you can turn off case insensitive mode using the minus sign:

`- grep: (?i)olympic|(?-i)Time Standard|2020`

**Comment by jprokos** [comment]
I am only able to get the (?i) flag to work. Other flags fail... e,F

Is there something I am missing or not understanding?

**Comment by jprokos** [comment]
Was not able to use the (?v) flag either to exclude items from grep search.

**Comment by jprokos** [comment]
I have this rule. I am trying to use grep to remove an item from results but I am having difficulty.


```name: MacRumors Apple Releases
kind: url
url: "https://www.macrumors.com"
filter:
 - xpath: '(//div[contains(@class,"wrapper")]//h2)/a'
 - grep: (?i)Apple Seeds|Apple Releases
 - html2text: re
---
```

These are the results:

```$ uwtf 22
Apple Seeds Fifth Beta of watchOS 6.2 to Developers
Apple Seeds Fifth Betas of iOS and iPadOS 13.4 to Developers [Update: Public Beta Available]
Apple Seeds Fifth Beta of Upcoming macOS Catalina 10.15.4 Update to Developers [Update: Public Beta Available]
Apple Seeds Fifth Beta of Upcoming tvOS 13.4 Update to Developers [Update: Public Beta Available]
```
I tried the following grep line but it fails with an error.

``` 
- grep: (?v)watchOS|(?i-v)Apple Seeds|Apple Releases
```
```
re.error: unknown extension ?v at position 1
```
Any idea how to exclude using grep or awk?

**Comment by cfbao** [comment]
> Was not able to use the (?v) flag either to exclude items from grep search.

`(?v)` is not a valid regex inline flags.

Again, urlwatch does NOT use the grep utility internally. The name of the filter is a bit misleading. It's regex only, not grep. See https://docs.python.org/3/library/re.html for references. Don't use grep's references.

**Comment by jprokos** [comment]
This may be a different issue but since we have this "help" thread going on grep I thought I would ask here.
urlwatch is accepting a grep format in one job but not in another which has me baffled. I thought the pipe could be used to separate strings, but obviously it doesn't like the` ' ` character next to the` | ` character. I tried to escape the pipe `\|` but it didn't like that either. I am trying to grep for two strings with a space between them and avoid the two words if they are not next to each other.

my job:

```
name: (30)MacRumors Apple Releases
kind: url
url: "https://www.macrumors.com"
filter:
 - xpath: '(//div[contains(@class,"article")]//h1)//a|//div[contains(@class,"byline")]'
 - grep: 'Apple Seeds'|'MacBook Air'
 - html2text: re
---
```

The error on exiting:
```
Parsing failed:
======
while scanning a block scalar
  in "/Users/john/Library/Application Support/urlwatch/urls.edit.yaml", line 185, column 23
expected chomping or indentation indicators, but found "'"
  in "/Users/john/Library/Application Support/urlwatch/urls.edit.yaml", line 185, column 24
======
```

The other job which is not flagged with a formatting error:

```
name: (25)SwimSwam News "NAG"
kind: url
url: https://swimswam.com/news
filter:
  - xpath:
      path: '(//div[contains(@class,"item")]//h3)/a|(//div[contains(@class,"item")]//h4)/a'
  - grep: (?i)'National Age Group'|'NAG'
---
```
