### ISSUE TITLE
XPATH issue on Mac

### ISSUE THREAD

**Issue by jprokos** [thp/urlwatch#453]
I am referring to the following author supplied example on a website and having an issue with pulling the second path.

```
url: 'https://heronebag.com/blog/index.xml'
filter:
  - xpath:
      path: '//item/title/text()|//item/pubDate/text()'
      method: xml
```

The first path pulls info but the second is not pulled for this site. What is the correct way?

My Filter:
```
name: SwimSwam News Feed
url: https://swimswam.com/news/feed/
filter:
  - xpath:
      path: '//item/title/text()|//item/pubDate/text()'
      method: xml
  - grep: '2020'
```

Page example of xml:
```
<item>
		<title>2020 Women&#8217;s B1G Day 4 Ups/Mids/Downs: Ohio State Earns 8 A-Final Swims</title>
		<link>https://swimswam.com/2020-womens-b1g-day-4-ups-mids-downs-ohio-state-earns-8-a-final-swims/</link>
				<comments>https://swimswam.com/2020-womens-b1g-day-4-ups-mids-downs-ohio-state-earns-8-a-final-swims/#respond</comments>
				<pubDate>Sat, 22 Feb 2020 23:00:16 +0000</pubDate>
		<dc:creator><![CDATA[Nick Pecoraro]]></dc:creator>
				<category><![CDATA[Big Ten]]></category>
		<category><![CDATA[College]]></category>
		<category><![CDATA[News]]></category>

```

The one obvious difference is that the example URL ends with `.xml` while the URL  I am scraping ends with `/feed.`

**Comment by cfbao** [comment]
Can you post your results from `urlwatch --test-filter` here? It's not clear what you mean, and what you expect.

With a job defined like this
```yaml
kind: url
url: https://swimswam.com/news/feed/
filter:
  - xpath:
      path: '//item/title/text()|//item/pubDate/text()'
      method: xml
```
I get this result:
```
Schoenmaker, Du Preez Get It Done In Durban To Close Out Grand Prix
Sun, 23 Feb 2020 17:58:23 +0000
San Diego State Wins Mountain West Champs, Highest Score in Conference History
Sun, 23 Feb 2020 17:37:37 +0000
2020 Horizon League Scoring Breakdown
Sun, 23 Feb 2020 17:30:20 +0000
Scott Scores 100 Fly/200 IM Double, Peaty Powers To 50 Breast Win At McCullagh
Sun, 23 Feb 2020 17:23:38 +0000
2020 ACC Women?? Scoring Breakdown
Sun, 23 Feb 2020 17:10:39 +0000
MacNeil Earns Another Honor, Wins Big Ten Swimmer of the Meet
Sun, 23 Feb 2020 17:05:46 +0000
Hayden Hits 22.40 In 50 Freestyle Prelim
Sun, 23 Feb 2020 16:52:49 +0000
Brent Hayden Lowers Season-Best 100 Free To 49.51, Threatens Kisil?? 49.48
Sun, 23 Feb 2020 15:45:22 +0000
WATCH: Auburn?? Record-Setting Relays, Women?? Race Videos from 2020 SECs
Sun, 23 Feb 2020 15:25:41 +0000
2020 B1G Women?? Scoring Breakdown
Sun, 23 Feb 2020 15:10:02 +0000
```
This is exactly as expected.

Adding the grep "2020" filter, so the job is
```yaml
kind: url
url: https://swimswam.com/news/feed/
filter:
  - xpath:
      path: '//item/title/text()|//item/pubDate/text()'
      method: xml
  - grep: '2020'
```
and the result is
```
Sun, 23 Feb 2020 17:58:23 +0000
Sun, 23 Feb 2020 17:37:37 +0000
2020 Horizon League Scoring Breakdown
Sun, 23 Feb 2020 17:30:20 +0000
Sun, 23 Feb 2020 17:23:38 +0000
2020 ACC Women?? Scoring Breakdown
Sun, 23 Feb 2020 17:10:39 +0000
Sun, 23 Feb 2020 17:05:46 +0000
Sun, 23 Feb 2020 16:52:49 +0000
Sun, 23 Feb 2020 15:45:22 +0000
WATCH: Auburn?? Record-Setting Relays, Women?? Race Videos from 2020 SECs
Sun, 23 Feb 2020 15:25:41 +0000
2020 B1G Women?? Scoring Breakdown
Sun, 23 Feb 2020 15:10:02 +0000
```
Again, this is what you'd expect.

**Comment by jprokos** [comment]
It looks like you amended my job slightly by adding `kind: url` where I just used `url: `

I wasn't tipped off to the "error" because I was getting results. I just copied the structure the author created, shown above, and used it for my page. He didn't use `kind: url` and both of his requests pulled when I tried them.

I understand I must edit my job, but I would like to know why the author's example didn't work for my site.

```
name: SwimSwam News Feed
url: https://swimswam.com/news/feed/
filter:
  - xpath:
      path: '//item/title/text()|/item/pubDate/text()'
      method: xml
---
```
I get these results:

```
See 2284 New Swim Jobs You Might Love
2020 Women’s Big 12 Fan Guide: Texas Looking at 8th Straight Title
2020 Men’s Big 12 Championships Fan Guide: Texas Eyeing 41st-Consecutive Title
Olympic Odds: Each Swimmer’s Probability Of Winning Gold In Tokyo
Pratt Picks Up Two More Golds On Night Two Of Cascade Trand Mountain Festival
Miami, Florida State Lead Men’s ACC Championships after Diving
Cascade Trans Mountain Festival: Hayden Nuota 22.31 E 49.51 Al Rientro
Mid-Major Mini Capsules: Champions and Award Winners From Week 2
Cancellata Para SWS E Campionato Italiano Invernale Paralimpico
#4 USC, #10 Michigan Score 2 Upsets Each to Lead WWP Week 6 Results
```

The same job using grep:

```
name: SwimSwam News Feed
url: https://swimswam.com/news/feed/
filter:
  - xpath:
      path: '//item/title/text()|/item/pubDate/text()'
      method: xml
  - grep: '2020'
---
```

I get these results:

```
2020 Women’s Big 12 Fan Guide: Texas Looking at 8th Straight Title
2020 Men’s Big 12 Championships Fan Guide: Texas Eyeing 41st-Consecutive Title
```

**Comment by jprokos** [comment]
It looks like you amended my job slightly by adding `kind: url` where I just used `url: `

I wasn't tipped off to the "error" because I was getting results. I just copied the structure the author created, shown above, and used it for my page. He didn't use `kind: url` and both of his requests pulled when I tried them.

Examples are from before adding `kind: url`

```
name: SwimSwam News Feed
url: https://swimswam.com/news/feed/
filter:
  - xpath:
      path: '//item/title/text()|/item/pubDate/text()'
      method: xml
---
```
I get these results:

```
See 2284 New Swim Jobs You Might Love
2020 Women’s Big 12 Fan Guide: Texas Looking at 8th Straight Title
2020 Men’s Big 12 Championships Fan Guide: Texas Eyeing 41st-Consecutive Title
Olympic Odds: Each Swimmer’s Probability Of Winning Gold In Tokyo
Pratt Picks Up Two More Golds On Night Two Of Cascade Trand Mountain Festival
Miami, Florida State Lead Men’s ACC Championships after Diving
Cascade Trans Mountain Festival: Hayden Nuota 22.31 E 49.51 Al Rientro
Mid-Major Mini Capsules: Champions and Award Winners From Week 2
Cancellata Para SWS E Campionato Italiano Invernale Paralimpico
#4 USC, #10 Michigan Score 2 Upsets Each to Lead WWP Week 6 Results
```

The same job using grep:

```
name: SwimSwam News Feed
url: https://swimswam.com/news/feed/
filter:
  - xpath:
      path: '//item/title/text()|/item/pubDate/text()'
      method: xml
  - grep: '2020'
---
```

I get these results:

```
2020 Women’s Big 12 Fan Guide: Texas Looking at 8th Straight Title
2020 Men’s Big 12 Championships Fan Guide: Texas Eyeing 41st-Consecutive Title
```
