### ISSUE TITLE
Regex issue and Question

### ISSUE THREAD

**Issue by jprokos** [thp/urlwatch#469]
urlwatch is accepting a grep format in one job but not in another which has me baffled. The pipe can be used to separate strings, but it doesn't like the` ' ` character next to the` | ` character. I tried to escape the pipe `\|` but it didn't like that either.

I am trying to grep for a pair of "two word" strings which a space between. My format works when checking it on [RegEx.com](https://regex101.com) when not using single quotes around the two word string, but fails within my urlwatch job without single quotes around the two words. The job finds `apple` as well as `apple releases`. If I use single quotes then I get an error as show below, but for only one of two jobs formatted that way.

`(?i)apple seeds|apple releases`

my job:

```
name: (30)MacRumors Apple Releases
kind: url
url: "https://www.macrumors.com"
filter:
 - xpath: '(//div[contains(@class,"article")]//h1)//a|//div[contains(@class,"byline")]'
 - grep: (?i)'apple seeds'|'apple releases'
 - html2text: re
---
```

The error on exiting:
```
Parsing failed:
======
while scanning a block scalar
  in "/Users/john/Library/Application Support/urlwatch/urls.edit.yaml", line 185, column 23
expected chomping or indentation indicators, but found "'"
  in "/Users/john/Library/Application Support/urlwatch/urls.edit.yaml", line 185, column 24
======
```

The other job which is not flagged with a formatting error:

```
name: (25)SwimSwam News "NAG"
kind: url
url: https://swimswam.com/news
filter:
  - xpath:
      path: '(//div[contains(@class,"item")]//h3)/a|(//div[contains(@class,"item")]//h4)/a'
  - grep: (?i)'National Age Group'|'NAG'
---
```

Please! What is the proper way to grep? It's not following Python RegEx rules as far as I can see.
