### ISSUE TITLE
xpath example included here

### ISSUE THREAD

**Issue by bbrendon** [thp/urlwatch#480]
After going through the issues, it seems like people (including myself) are struggling to leverage the power of this tool. After a bit of work digging through MS docs, the readme, and the source code, I made this which seems to work and may provide a good example for others. In the below, the "grid-wrapper" is included and the "sidebar" is removed (which is part of "grid-wrapper").

I'd love to know a better way to get the expected outcome but this seems to work for now.

```
kind: url
name: hass blog
url: https://www.home-assistant.io/blog/
filter:
  - xpath:
      path: '(//div[contains(@class,"grid-wrapper")])'
      exclude: '(//*[contains(@id,"sidebar")])'
  - html2text: re
  - strip:


```
