### ISSUE TITLE
`command` output is missing, but works during --test-filter

### ISSUE THREAD

**Issue by iandundas** [thp/urlwatch#488]
Hi,

I have a `urls.yaml` that looks like this: 

```yaml
name: "XCode Releases"
command: curl -s https://xcodereleases.com/data.json | jq '.[0] | .version'
---
name: "Swift Releases"
command: curl -s https://xcodereleases.com/data.json | jq '.[0] | .compilers.swift'

```

When I run `urlwatch --test-filter 1` the output is correct: 

```json
{
  "number": "11.5",
  "build": "11N605f",
  "release": {
    "beta": 2
  }
}
```

So far so good!

However, what I receive (in Telegram, and at the console) when I run `urlwatch` is only the name of the Job, not the output: 

```
urlwatch
===========================================================================
01. NEW: Swift Releases
02. NEW: XCode Releases
===========================================================================

---------------------------------------------------------------------------
NEW: Swift Releases ( curl -s https://xcodereleases.com/data.json | jq '.[0] | .compilers.swift' )
---------------------------------------------------------------------------


---------------------------------------------------------------------------
NEW: XCode Releases ( curl -s https://xcodereleases.com/data.json | jq '.[0] | .version' )
---------------------------------------------------------------------------


--
urlwatch 2.18, Copyright 2008-2020 Thomas Perl
Website: https://thp.io/2008/urlwatch/
watched 2 URLs in 0 seconds
```

Can anyone point me to what's going wrong here? thanks!
