### ISSUE TITLE
urlwatch --list shows only last job

### ISSUE THREAD

**Issue by SHU-red** [thp/urlwatch#551]
Hello,
for some reason urlwatch only recognizes the last job!
Am i doing somthing wrong in my edit-file or is it a bug?

Edit-File
```
name: "GARMIN Instinct - Firmware"
url: "https://www8.garmin.com/support/download_details.jsp?id=14527"
filter:
  - html2text:
  - grep: ".*software version.*"
  - strip:

name: "GARMIN GPS Chipset Type M5 - Firmware"
url: "https://www8.garmin.com/support/download_details.jsp?id=15023"
filter:
  - html2text:
  - grep: ".*software version.*"
  - strip:

name: "GARMIN Edge 530 - Firmware"
url: "https://www8.garmin.com/support/download_details.jsp?id=14885"
filter:
  - html2text:
  - grep: ".*software version.*"
  - strip:

name: "Android Developers - OTA files"
url: "https://developers.google.com/android/ota"
filter:
  - html2text:

name: "GitTest"
url: "https://github.com/SHU-red/PyGrd"
filter:
  - html2text:
  - grep: ".*Enjoy and give.*"
  - strip:

name: "Kenwood KMM-BT204 - Firmware"
url: "https://www.kenwood.com/cs/ce/receiver/firmware/2018/2018e/deu.html"
filter:
  - html2text:
```

Feedback after urlwatch --list
`1: Kenwood KMM-BT204 - Firmware (https://www.kenwood.com/cs/ce/receiver/firmware/2018/2018e/deu.html)`

So all of the stuff from above is missing and not recognized/checkted by urlwatch

Im using Urlwatch 2.16 on my raspberry pi
```
pi@retropie:~ $ lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
```

**Comment by SHU-red** [comment]
For your information:
Upgraded to urlwatch 2.21 --> Problem still there

**Comment by thp** [comment]
You need to separate the jobs with a line containing ---, so that it is a
YAML list:

```yaml
---
```

SHU-red <notifications@github.com> schrieb am Mi., 12. Aug. 2020, 17:15:

**Comment by thp** [comment]
You need to separate each entry with `---`, as per YAML.

**Comment by thp** [comment]
Example:
```
name: "GitTest"
url: "https://github.com/SHU-red/PyGrd"
filter:
  - html2text:
  - grep: ".*Enjoy and give.*"
  - strip:
---
name: "Kenwood KMM-BT204 - Firmware"
url: "https://www.kenwood.com/cs/ce/receiver/firmware/2018/2018e/deu.html"
filter:
  - html2text:
```
