### ISSUE TITLE
grep - Multiline-Filtering Problem

### ISSUE THREAD

**Issue by SHU-red** [thp/urlwatch#556]
Hello,
im writing here because im not sure if the problem i have is urlwatch-specific?

After filter html2text i get for example:
```
Unix-Treiber
     WICHTIGE LINKS
      Download Drivers
     Linux x86_64/AMD64/EM64T
       Letzte langlebige Branch Version: 450.66
      Letzte kurzlebige Branch Version: 435.21
      415.18-->
      Letzte Legacy GPU Version (390.xx Serie): 390.138
      Letzte Legacy GPU Version (340.xx Serie): 340.108
      Letzte Legacy GPU Version (304.xx Serie): 304.137
      Letzte Legacy GPU Version (71.86.xx Serie): 71.86.15
      Letzte Legacy GPU Version (96.43.xx Serie): 96.43.23
      Letzte Legacy GPU Version (173.14.xx Serie): 173.14.39
      Archiv
     Linux x86/IA32
      Letzte Legacy GPU Version (390.xx Serie): 390.138
      381.22-->
      Letzte Legacy GPU Version (340.xx Serie): 340.108
      Letzte Legacy GPU Version (304.xx Serie): 304.137
      Letzte Legacy GPU Version (71.86.xx Serie): 71.86.15
```

I tested this grep expression on "online regex-testers"
`x86_64([\S\s]*?)Archiv`
This should give me all the text between "x86_64" and "Archiv" which is also highlighted at the online-testers, giving me as result:
```
x86_64/AMD64/EM64T
       Letzte langlebige Branch Version: 450.66
      Letzte kurzlebige Branch Version: 435.21
      415.18-->
      Letzte Legacy GPU Version (390.xx Serie): 390.138
      Letzte Legacy GPU Version (340.xx Serie): 340.108
      Letzte Legacy GPU Version (304.xx Serie): 304.137
      Letzte Legacy GPU Version (71.86.xx Serie): 71.86.15
      Letzte Legacy GPU Version (96.43.xx Serie): 96.43.23
      Letzte Legacy GPU Version (173.14.xx Serie): 173.14.39
      Archiv
```

If im using the same expression as grep in urlwatch im getting only a empty row when using it with urlwatch --test-filter 8

For sure im doing something wrong, but tested different variations and could not figure out why.
Maybe you have a different grep-solution for "Getting all changes (incl. multiline) between two words"

Thanks and sorry if this is a "beginner-question"

**Comment by thp** [comment]
Can you post your full filter settings? Have you tried with `shellpipe`?

**Comment by SHU-red** [comment]
Hey,
thanks for the fast repliy
```
name: 'NVIDIA - UNIX Drivers'
url: 'https://www.nvidia.com/de-de/drivers/unix/'
filter:
  - html2text:
  - grep: 'x86_64([\S\s]*?)Archiv'
```
No i didnt ...
I will check what it is and try

I just first used only the html2text filter to see whats the basis for the grep command
After that i added grep with the stuff i "simulated" bevore in the regex-online-testers to make sure my regex-expression is correct

**Comment by thp** [comment]
The following works for me:

```
name: 'NVIDIA - UNIX Drivers'
url: 'https://www.nvidia.com/de-de/drivers/unix/'
filter:
  - html2text: pyhtml2text
  - shellpipe: "perl -ne '/Linux x86_64/../Archiv/ and print'"
```

Explanation:

It first uses `pyhtml2text` to convert the HTML to text (in my tests this provides the nicest output for that particular page).

Then it uses `perl` (with the recipe from [How to print lines between two patterns, inclusive or exclusive (in sed, AWK or Perl)?](https://stackoverflow.com/a/55773449/1047040) on StackOverflow) to filter from the line containing `Linux x86_64` to the line containing `Archiv`.

The `shellpipe` filter needs urlwatch 2.19 or newer, and you obviously need to have `perl` installed on your system (the StackOverflow link above also contains alternative solutions using `sed` or `awk`).

**Comment by SHU-red** [comment]
Puh ...
somehow i cant use " for commands like grep and shellpipe, thats why i have to use:
```
name: 'NVIDIA - UNIX Drivers'
url: 'https://www.nvidia.com/de-de/drivers/unix/'
filter:
  - html2text: pyhtml2text
  - shellpipe: 'perl -ne "/Linux x86_64/../Archiv/ and print"'
```
this i can save without errors, but if i execute it it says:
```
Traceback (most recent call last):
  File "/home/pi/.local/bin/urlwatch", line 10, in <module>
    sys.exit(main())
  File "/home/pi/.local/lib/python3.7/site-packages/urlwatch/cli.py", line 112, in main
    urlwatch_command.run()
  File "/home/pi/.local/lib/python3.7/site-packages/urlwatch/command.py", line 402, in run
    self.handle_actions()
  File "/home/pi/.local/lib/python3.7/site-packages/urlwatch/command.py", line 204, in handle_actions
    sys.exit(self.test_filter(self.urlwatch_config.test_filter))
  File "/home/pi/.local/lib/python3.7/site-packages/urlwatch/command.py", line 137, in test_filter
    raise job_state.exception
  File "/home/pi/.local/lib/python3.7/site-packages/urlwatch/handler.py", line 113, in process
    data = FilterBase.process(filter_kind, subfilter, self, data)
  File "/home/pi/.local/lib/python3.7/site-packages/urlwatch/filters.py", line 146, in process
    return filtercls(state.job, state).filter(data, subfilter)
  File "/home/pi/.local/lib/python3.7/site-packages/urlwatch/filters.py", line 293, in filter
    method=method, options=options)
  File "/home/pi/.local/lib/python3.7/site-packages/urlwatch/html2txt.py", line 62, in html2text
    import html2text
ModuleNotFoundError: No module named 'html2text'

```

But html2text: im using very often for all of my other filters

**Comment by thp** [comment]
You can also use the regex-based html2text filter:

```
name: 'NVIDIA - UNIX Drivers'
url: 'https://www.nvidia.com/de-de/drivers/unix/'
filter:
  - html2text: re
  - shellpipe: 'perl -ne "/Linux x86_64/../Archiv/ and print"'
```

**Comment by SHU-red** [comment]
OK i think i got it!
The solution was the "perl" command i think

When i now use this code
```
name: 'NVIDIA - UNIX Drivers'
url: 'https://www.nvidia.com/de-de/drivers/unix/'
filter:
  - html2text:
  - shellpipe: 'perl -ne "/Linux x86_64/../Archiv/ and print"'
```

I get this feedback (... which is my target)
```
     Linux x86_64/AMD64/EM64T
       Letzte langlebige Branch Version: 450.66
      Letzte kurzlebige Branch Version: 435.21
      415.18-->
      Letzte Legacy GPU Version (390.xx Serie): 390.138
      Letzte Legacy GPU Version (340.xx Serie): 340.108
      Letzte Legacy GPU Version (304.xx Serie): 304.137
      Letzte Legacy GPU Version (71.86.xx Serie): 71.86.15
      Letzte Legacy GPU Version (96.43.xx Serie): 96.43.23
      Letzte Legacy GPU Version (173.14.xx Serie): 173.14.39
      Archiv
```

So i guess using the standard grep-filter is not working for multiline-stuff?

Thanks Thomas! You are a magician! ;-)
