### ISSUE TITLE
is there a way make urlwatch only tell me some webpage has changed, but not output anything.

### ISSUE THREAD

**Issue by A6669** [thp/urlwatch#576]
I use urlwatch to watch some websites, sometimes urlwatch output so much stuff, so is there a way to make urlwatch only tell me some webpage has changed, but do not output anything. I will check what has changed.

**Comment by thp** [comment]
Use `urlwatch --edit-config` and then set this:

```
report:
  text:
    details: false
```

**Comment by A6669** [comment]
> Use `urlwatch --edit-config` and then set this:
> 
> ```
> report:
>   text:
>     details: false
> ```
thank you, but I  want to show the detail of some websites I monitor,  not to show the detail of some others, what should I do?

**Comment by thp** [comment]
You could set a diff filter on the job that ignores its stdin (the diff) and does something like this:

```
diff_filter:
  - shellpipe: 'echo "Diff omitted"'
```

**Comment by A6669** [comment]
thank you

> You could set a diff filter on the job that ignores its stdin (the diff) and does something like this:
> 
> ```
> diff_filter:
>   - shellpipe: 'echo "Diff omitted"'
> ```

is it OK? if I set up as below
```
name: "aaa"
navigate: "aaa.com"
max_tries: 5
filter:
  - xpath: '/html/body/main'
  - html2text:
      method: pyhtml2text
      unicode_snob: true
      body_width: 0
      inline_links: false
      ignore_links: true
      ignore_images: true
      pad_tables: false
      single_line_break: true
  - diff_filter:
      shellpipe: 'echo "Diff omitted"' 
```

**Comment by thp** [comment]
It should be "next to" the other items, so:

```
name: "aaa"
navigate: "aaa.com"
max_tries: 5
filter:
  - xpath: '/html/body/main'
  - html2text:
      method: pyhtml2text
      unicode_snob: true
      body_width: 0
      inline_links: false
      ignore_links: true
      ignore_images: true
      pad_tables: false
      single_line_break: true
diff_filter:
  - shellpipe: 'echo "Diff omitted"' 

```

**Comment by A6669** [comment]
can I just write as below?
```
name: "aaa"
navigate: "aaa.com"
max_tries: 5
filter:
  - xpath: '/html/body/main'
diff_filter:
  - shellpipe: 'echo "Diff omitted"' 
```
