### ISSUE TITLE
Question Inconsistent behavior on RSS jobs

### ISSUE THREAD

**Issue by jprokos** [thp/urlwatch#586]
```
name: 22_SwimSwam News [USA Swimming, Time Standard, National Age Group]
url: https://swimswam.com/feed/
filter:
  - xpath:
      path: '//item/description/text()'
      exclude: a
      method: xml
  - grep: (?i)"usa.*swimming"|"time.*standard"|"national.*age.*group"
  - html2text: re
---
name: 23_SwimSwam News [NAG]
url: https://swimswam.com/feed/
filter:
  - xpath:
      path: '//item/description/text()'
      exclude: a
      method: xml
  - shellpipe: "grep 'NAG'; > /dev/null 2>&1"
  - html2text: re
---
```

Every time urlwatch runs this alternates between being "found" and not being "found". Not sure what is happening here. It's an RSS feed and I know the string 'NAG' is still in the feed.
```
Fri Oct 16 08:50:24
iMac191:~ john$ urlwatch
==========
01. CHANGED: 22_SwimSwam News [USA Swimming, Time Standard, National Age Group]
==========

----------
CHANGED: 22_SwimSwam News [USA Swimming, Time Standard, National Age Group] ( https://swimswam.com/feed/ )
----------
--- @	Fri, 16 Oct 2020 20:46:00 -0500
+++ @	Fri, 16 Oct 2020 20:50:40 -0500
@@ -1 +0,0 @@
-Read the full story on SwimSwam: Carson Foster Obliterates 400 IM 17-18 NAG, Moves to #2 All-Time, With 3:35.27
----------


Fri Oct 16 08:50:41
iMac191:~ john$ urlwatch
==========
01. CHANGED: 23_SwimSwam News [NAG]
==========

----------
CHANGED: 23_SwimSwam News [NAG] ( https://swimswam.com/feed/ )
----------
--- @	Fri, 16 Oct 2020 20:50:39 -0500
+++ @	Fri, 16 Oct 2020 20:51:32 -0500
@@ -0,0 +1 @@
+Read the full story on SwimSwam: Carson Foster Obliterates 400 IM 17-18 NAG, Moves to #2 All-Time, With 3:35.27
----------


Fri Oct 16 08:51:33
iMac191:~ john$ urlwatch
==========
01. CHANGED: 22_SwimSwam News [USA Swimming, Time Standard, National Age Group]
==========

----------
CHANGED: 22_SwimSwam News [USA Swimming, Time Standard, National Age Group] ( https://swimswam.com/feed/ )
----------
--- @	Fri, 16 Oct 2020 20:51:31 -0500
+++ @	Fri, 16 Oct 2020 20:51:43 -0500
@@ -1 +0,0 @@
-Read the full story on SwimSwam: Carson Foster Obliterates 400 IM 17-18 NAG, Moves to #2 All-Time, With 3:35.27
----------
```

**Comment by thp** [comment]
This is #153, you are trying to use the same URL for multiple jobs. This does not work.

Make sure each job has a unique URL, you can work around it by adding `#something` to the URLs, this makes them unique, but doesn't change the HTTP request path:

```yaml
name: 22_SwimSwam News [USA Swimming, Time Standard, National Age Group]
url: https://swimswam.com/feed/#first
filter:
  - xpath:
      path: '//item/description/text()'
      exclude: a
      method: xml
  - grep: (?i)"usa.*swimming"|"time.*standard"|"national.*age.*group"
  - html2text: re
---
name: 23_SwimSwam News [NAG]
url: https://swimswam.com/feed/#second
filter:
  - xpath:
      path: '//item/description/text()'
      exclude: a
      method: xml
  - shellpipe: "grep 'NAG'; > /dev/null 2>&1"
  - html2text: re
---
```
