### ISSUE TITLE
Feature request: support optional key `disabled`

### ISSUE THREAD

**Issue by snowman** [thp/urlwatch#625]
- `disabled`: disable watch (default: False)

When set to `True`, do not watch the specified entry.

**Comment by cfbao** [comment]
does using YAML comment not do what you need?

[YAML syntax - Wikipedia](https://en.wikipedia.org/wiki/YAML#Syntax)

**Comment by snowman** [comment]
sorry for not clarifying the issue, currently I use comments to disable watching them.

When you have a long urlwatch entry, by using comments, you have to
1. Comment multiple lines of text
2. Once commented, they don't provide breadcrumb menus to navigate when using VS Code or Emacs.

```yaml
# ---
# name: "LOL version update"
# url: "http://lol.qq.com/gicp/news/423/2/1334/1.html"
# encoding: gbk
# filter:
#   - css: '.news-type-list .newsitem'
#   - css: '.item-href, .item-time'
#   - html2text
#   - shellpipe: awk 'NR % 2 == 1 { description=$0; } NR % 2 == 0 { printf "%s - %s\n", $0, description; }'
#   - re.sub:
#       pattern: '版本更新公告[^：]*?：'
#       repl: ': '
#   - re.sub:
#       pattern: '(\b[0-9]{2})\.([0-9])\b'
#       repl: '\1.0\2'
```

```yaml
---
name: "LOL version update"
disabled: true               ## Only change one line, more friendly if you are using git
url: "http://lol.qq.com/gicp/news/423/2/1334/1.html"
encoding: gbk
filter:
  - css: '.news-type-list .newsitem'
  - css: '.item-href, .item-time'
  - html2text
  - shellpipe: awk 'NR % 2 == 1 { description=$0; } NR % 2 == 0 { printf "%s - %s\n", $0, description; }'
  - re.sub:
      pattern: '版本更新公告[^：]*?：'
      repl: ': '
  - re.sub:
      pattern: '(\b[0-9]{2})\.([0-9])\b'
      repl: '\1.0\2'
```
