### ISSUE TITLE
Documentation about monitoring GitHub

### ISSUE THREAD

**Issue by mhalano** [thp/urlwatch#662]
Could have a section in documentation about monitoring new releases/tags in GitHub using the API and jq filter. I created something like that and work pretty well:
```yaml
name: 'Rundeck Puppet module new release'
url: 'https://api.github.com/repos/voxpupuli/puppet-rundeck/tags'
filter:
  - jq: '.[0].name' 
```
