### ISSUE TITLE
Help request for Amazon price tracker with urlwatch

### ISSUE THREAD

**Issue by Jorman** [thp/urlwatch#688]
Hi, I'm trying to build a simple price tracker for Amazon products, for example this one:
![image](https://user-images.githubusercontent.com/5203988/148103886-cac4c9ff-8e69-4dbb-b81a-7f37e880a18f.png)
Note that as the language changes, so does Amazon's HTML, but I don't think the principle changes.

My current configuration is this:
```
name: "Test product"
url: "https://www.amazon.it/dp/B007427SAC/"
max_tries: 5
filter:
  - css:
      selector: '#corePrice_feature_div > div > span'
      maxitems: 1
  - beautify
  - html2text
  - grep: '[0-9]+[.,][0-9]{0,2}'
diff_filter:
  - grep: '^[@+]'
```
But I get strange response, sometimes the price is the same, but I get notification too, sometimes the price is not even present, I think is some kind of Amazon strange response, I usually check the page every 30 min. Here are some logs, maybe someone with better knowledge can tell me what I do wrong.

Log without changes but notified sent:
[with.log](https://github.com/thp/urlwatch/files/7810583/with.log)

Log with changes and notified:
[without.log](https://github.com/thp/urlwatch/files/7810588/without.log)

Why if the price is always the same do I get a notification?

J

**Comment by kongomongo** [comment]
maybe some non-printable chars are detected as diff?

**Comment by Jorman** [comment]
Hi, actually the code is this:
```
name: "Test product"
url: "https://www.amazon.it/dp/B007427SAC/"
max_tries: 5
filter:
  - css:
      selector: '#corePrice_feature_div > div > span > span.a-offscreen'
      maxitems: 1
  - beautify
  - grep: '([0-9]+[.,][0-9]{0,2}€)'
diff_filter:
  - grep: '^[@+]'
```
I changed it a little bit, but sometimes I get notification with empty changes

**Comment by kongomongo** [comment]
just to be sure: since you are omitting "deleted" lines in diff_filter you WILL be notified of an empty diff if there are ONLY deleted lines.

This is because after the diff has been calculated, the diff_filter only cosmetically changes the output to the reporter. It CAN NOT prevent a diff to be reported.

**Comment by Jorman** [comment]
Ok, make sense.
I don't know well how to set it up correctly, the idea is simple keep track of the price and notify when it changes
I also tried with shellpipe, but I don't know how to "pass" the results.

Do you've a better idea?

**Comment by JsBergbau** [comment]
I'm using a similar solution for Amazon for quite some time. 

```
name: "UGreen Adapter"
url: https://www.amazon.de/UGREEN-Konverter-Festplatten-Dockingstation-Netzadapter/dp/B016UBXH3O
compared_versions: 2
headers:
    User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0
    Cookie: XXXXXX
filter:
    - xpath: //*[@id="priceblock_ourprice"]
    - html2text: re
```

I explicitly use User-Agent and Header copied from my browser. However Amazon detects this after some time and if you then test the filter without xpath expression you will get a response that says something like don't do this, Amazon has an API for getting the price. 

Sometimes (without changing the IP adress or anything else in the configuration) price is present again. Thats why I used `compared_versions: 2`

So it comares empty price with "real" price. However you don't know when Amazon delivers the website with the price. Thats why I'm using [Keepa ](https://keepa.com) now.
