### ISSUE TITLE
How to use environment variables in URLs?

### ISSUE THREAD

**Issue by throwaway29345** [thp/urlwatch#701]
I have a question on using environment variables in side a job.

```yaml
name: "my job"
url: https://mysite.org?api_key=${env variable}
filter:
  - some filter...
```

Is this possible today?
