### ISSUE TITLE
not able to correctly load page for homedepot and walmart

### ISSUE THREAD

**Issue by sentinel3** [thp/urlwatch#705]
Hi great tool! I just set `urlwatch` up and it works on one test page. but when I further explore and put into one product on HomeDepot and Walmart, they both failed.
```
$cat urls.yaml
name: "HomeDepot"
url: "https://www.homedepot.ca/product/hampton-bay-1-person-braided-woven-egg-patio-swing/1001582001"
filter:
    - xpath: //span[@class="hdca-product__description-pricing-price-value"]
    - html2text
---
name: "Walmart"
url: "https://www.walmart.ca/en/ip/hometrends-egg-swing-with-stand-black/6000203713927"
filter:
  - xpath: //span/span[@class="css-2vqe5n esdkp3p0" and @data-automation="buybox-price"] 
  - html2text
```
then I tried to test the filters for  **Homedepot** list:
`urlwatch --test-filter` and both give me empty result.
I further commented the `xpath` in `filter` in the above settings. and run with `verbose`:
```
$urlwatch --test-filter 1 --verbose #xpath filter commented
...
...connectionpool DEBUG: Starting new HTTPS connection (1): www.homedepot.ca:443
```
for this Homedepot list, it hangs here!  I further followed the #575 to add: `##headers:    User-Agent: <redacted>`, then it runs but still no result.

then I tried to test the filters for  **Walmart** list:
```
$urlwatch --test-filter 2 --verbose #xpath filter commented
Skip to main ...
JavaScript is Disabled
      Sorry, this webpage requires JavaScript to function correctly.
      Please enable JavaScript in your browser and reload the page.
```
I tried suggestion of #465, and tried to download the walmart page directly: `curl` directly replies `blocked`, while `wget` will download a page with text:
```
Are you human?
Seems like a silly question, we know. But, we want to keep robots off of Walmart.ca! 
```
seems Walmart blocks such automatic watch?

any help is appreciated.
thx
