### ISSUE TITLE
Applying same options to multiple URLs

### ISSUE THREAD

**Issue by jwilk** [thp/urlwatch#719]
I'm watching a large number of URLs that have the same structure, so I'm applying the same set of filters to them:

```yaml
url: https://example.net/9566
ssl_no_verify: true
filter:
- css: '#data'
- xpath: '//text()'
- format-json: null
- grep: '"(foo|bar)":'
- re.sub: 'T00:00:00(?=")'
- re.sub: '"'
- re.sub: '(?m)^ *|,$'
---
url: https://example.net/14026
ssl_no_verify: true
filter:
- css: '#data'
- xpath: '//text()'
- format-json: null
- grep: '"(foo|bar)":'
- re.sub: 'T00:00:00(?=")'
- re.sub: '"'
- re.sub: '(?m)^ *|,$'
---
url: https://example.net/15829
ssl_no_verify: true
filter:
- css: '#data'
- xpath: '//text()'
- format-json: null
- grep: '"(foo|bar)":'
- re.sub: 'T00:00:00(?=")'
- re.sub: '"'
- re.sub: '(?m)^ *|,$'
---
# ...
```

This is very tiresome to update.

So I wish I could write something like this instead:

```yaml
url:
- https://example.net/9566
- https://example.net/14026
- https://example.net/15829
# ...
ssl_no_verify: true
filter:
- css: '#data'
- xpath: '//text()'
- format-json: null
- grep: '"(foo|bar)":'
- re.sub: 'T00:00:00(?=")'
- re.sub: '"'
- re.sub: '(?m)^ *|,$'
```
