### ISSUE TITLE
Shell reporter not working

### ISSUE THREAD

**Issue by notDavid** [thp/urlwatch#740]
Hi there, so I'm trying https://github.com/thp/urlwatch/commit/7c505657c7ccfe78060240ef5f09b21fd86cea13 but i can't get it to work;

it seems whatever i do, nothing is reported. If i disable all other reporters, and only keep the `shell` one, i get: `reporters WARNING: No reporters enabled.`

It seems as if it's not being triggered? In `urlwatch.yaml` i've configured:
```
report:
  shell:
    # command: ['/home/ubuntu/.local/bin/ntfyr', '--topic', 'hello', '--title', 'urlwatch']
    command: ['tee', '-a', '/home/ubuntu/tmp/log.txt']
    ignore_stdout: false
    enabled: true
```
No errors are logged. Could it be some bug in de code?
Please advise :-)

-- urlwatch 2.25
