### ISSUE TITLE
`.. code-block` seems to not be rendering properly

### ISSUE THREAD

**Issue by polyzen** [thp/urlwatch#750]
I see the docs are generated with quite an old version of Sphinx, maybe this has been fixed since then. If so, code blocks should probably all be made to use `.. code-block`.

**Comment by thp** [comment]
You mean the docs on https://urlwatch.readthedocs.io/en/latest/ or the ones that one can build locally?

**Comment by polyzen** [comment]
The deployed docs

**Comment by polyzen** [comment]
eg. https://urlwatch.readthedocs.io/en/latest/advanced.html#setting-the-content-width-for-html2text-lynx-method

**Comment by thp** [comment]
Looks okay from here:

![image](https://user-images.githubusercontent.com/135241/231138972-5e216b60-546c-4c35-9a19-06fbd3e72f47.png)

With this source:

```
.. code-block:: yaml

   url: http://example.com/longlines.html
   filter:
     - html2text:
         method: lynx
         width: 400
```

Which browser/settings are you using?
