### ISSUE TITLE
It's possible to avoid "403 Client Error: Forbidden for url" with url function?

### ISSUE THREAD

**Issue by Jorman** [thp/urlwatch#765]
Hi, I'm trying to configure a very simple url, is a simple site where you find used items, no log-in required, and nothing special is needed. If I try a simple wget with the url, it downloads the page, but if I use the url in the urlwatch configuration it returns error
`403 Client Error: Forbidden for url`
The only way I found to not get error is to configure urlwatch with "navigate" instead of "url", but of course it is much slower. Is there any way to understand why "url" mode doesn't work with this site?

If you want to try this is my configuration:
```
name: "Test"
navigate: "https://www.subito.it/annunci-italia/vendita/auto/suzuki/?q=suzuki+vitara"
filter:
  - css:
      selector: 'div.ItemListContainer_container__SjEc1 > p'
diff_filter:
  - grep: '^[@+]'
```
Any ideas?
