### ISSUE TITLE
`--test-reporter` option is ignoring separated flag

### ISSUE THREAD

**Issue by marunjar** [thp/urlwatch#771]
Since 2.26 it is possible to report jobs separately (see #721)
With this config for mail reporter (similar to example from docs) mails should be sent separated because of `separate: true`

```
report:
  email:
    enabled: true
    from: 'someone'
    html: true
    method: sendmail
    sendmail:
      path: /usr/sbin/sendmail
    smtp:
      auth: true
      host: localhost
      port: 25
      starttls: true
      user: ''
    subject: '{count} changes: {jobs}'
    to: 'someone'
  html:
    diff: unified
    separate: true
  text:
    details: true
    footer: true
    line_length: 80
    minimal: true
    separate: true
```

But when calling urlwatch with `--test-reporter email` option only single mail containing `3 changes: Newly Added, Something Changed, Error Reporting` is sent.

When calling urlwatch without `--test-reporter` option, everything is fine and mails for jobs are sent separated.
