### ISSUE TITLE
Reporting blanks

### ISSUE THREAD

**Issue by jkmaxwell** [thp/urlwatch#779]
I believe there is an error happening but I cannot confirm it and am therefore considering it a possible bug.

Summary:
I am getting empty notifications. I believe I should not be, given my parameters.

# urlwatch.yaml
Relevant sections
```
display:
  empty-diff: false
  error: true
  new: true
  unchanged: false
```
Reporting via email and pushover

# urls.yaml
```
name: "Dahlias Maks Georgia"
navigate: "https://lobaughsdahlias.com/product/maks-georgia-2020-introduction/"
browser: chromium
wait_until: load
filter:
  - css:
      selector: div.column.purchase-options-container.span-6
  - html2text
  - strip
diff_filter:
  - grep: -v 'Out of stock'
diff_tool: "diff --ignore-all-space --unified"
```
(i already tried with url instead of playwright, but i'm trying to outrun the dynamic content and it seems impossible)

# Logs
## test-diff-filter
```
xxx@xxx ~ % urlwatch --test-diff-filter 2
=== Filtered diff between state 0 and state 1 ===

=== Filtered diff between state 1 and state 2 ===

=== Filtered diff between state 2 and state 3 ===

=== Filtered diff between state 3 and state 4 ===

=== Filtered diff between state 4 and state 5 ===

=== Filtered diff between state 5 and state 6 ===
```

## test-filter
```
xxx@xxx ~ % urlwatch --test-filter 2     
Maks Georgia
$16.00
Out of stock
		SKU: 107
	Category: Dahlia
```

# Problem
However, I continually get positive hits and these generate reporter actions

```
===========================================================================
01. NEW: Dahlias Maks Georgia
02. NEW: Dahlias Honey
===========================================================================

---------------------------------------------------------------------------
NEW: Dahlias Maks Georgia ( https://lobaughsdahlias.com/product/maks-georgia-2020-introduction/ )
---------------------------------------------------------------------------


---------------------------------------------------------------------------
NEW: Dahlias Honey ( https://lobaughsdahlias.com/product/newaukum-honey/ )
---------------------------------------------------------------------------


-- 
urlwatch 2.28, Copyright 2008-2023 Thomas Perl
Website: https://thp.io/2008/urlwatch/
Support urlwatch development: https://github.com/sponsors/thp
watched 3 URLs in 2 seconds
```

Thank you!
