### ISSUE TITLE
Feature request: Extension of regex filtering to extract data

### ISSUE THREAD

**Issue by f0sh** [thp/urlwatch#804]
I couldn't find a way, how to use `re.sub` to extract data as a filter in urlwatch. Unless I haven't overseen anything, and there is a way to do it, I would like to open a feature request.

According to #401 I would like to request an extensions of the regex filtering. Instead of replacing matched strings, it would be useful to have a positive regex filter, to extract specific data. An example of this filtering is even in the [documentation](https://urlwatch.readthedocs.io/en/latest/filters.html#using-a-shell-script-as-a-filter). However there it is implemented using shellpipes and grep, but for me it turned out to be a bit unstable.

```
url: https://example.net/shellpipe-grep.txt
filter:
  - shellpipe: "grep -i -o 'price: <span>.*</span>'"
```

IMO better approach would be to have a filter like `re.findall` which goes along with `re.sub`:

```
url: https://example.net/pricelist.html
filter:
  - re.findall: 'price: <span>(.*)</span>'
```

**Comment by Jamstah** [comment]
`grep` and `grepi` can be used directly, so you could do something like:

```yaml
filter:
  - grepi: 'price: <span>.*</span>'
  - re.sub:
      pattern: '^.*(price: <span>.*</span>).*$'
      repl: '\1'
```
